### ISSUE TITLE
User feedback - open/closed indicator

### ISSUE THREAD

**Issue by aNullValue** [hackforla/ballotnav#343] opened 2021-01-05 17:34 UTC
"Why is the open icon green if the location is closed?"

(Comments gathered from friends of @aNullValue 2021-01-05.)

**Comment by Arjayellis** [comment] 2021-01-11 04:36
@tan-nate Can we make the icon green when open and red when closed?

**Comment by jmensch1** [comment] 2021-03-23 18:39
closing this as a duplicate of #272

**Closed by jmensch1** 2021-03-23 18:39 UTC
Labels: role: front end, size: medium
